spring:
<<<<<<< HEAD

  datasource:
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
    password: 74809903

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: question-service

=======
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: question-service
>>>>>>> origin/coder
