server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support_bridge
    username: postgres
    password: root123


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/