server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
    password: 74809903


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/