server:
  port: 8085

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
    password: 74809903
  ##  password: root123
=======
    url: jdbc:postgresql://localhost:5432/demo2
    username: ${USERNAME}
    password: ${PASSWORD}
>>>>>>> coder

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/