server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
<<<<<<< HEAD
    password: root123
=======
    password: 74809903
  ##  password: root123
>>>>>>> ec407483f6aee4b8446867eba26014d76d454560

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/