POST localhost:8090/auth/register
Content-Type: application/json

{
  "username": "john",
  "email": "aliyev",
  "password": "123"
}

###

POST localhost:8090/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "123"
}

###

GET localhost:8090/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huIiwiaWF0IjoxNjg3NTkzNjA1LCJleHAiOjE2ODc4MDk2MDV9.Nq3Cad401_Xm5TYM9j_OsVQxB4-ZjENYUNUgPJtKpGg

