server:
<<<<<<< HEAD
port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
    password: 74809903

  jpa:
    hibernate:
      ddl-auto: create
=======
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo2
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
>>>>>>> coder
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/