server:
<<<<<<< HEAD
<<<<<<< HEAD
port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support-bridge
    username: postgres
    password: 74809903

  jpa:
    hibernate:
      ddl-auto: create
=======
=======
>>>>>>> origin/coder
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo2
<<<<<<< HEAD
    username: ${USERNAME}
    password: ${PASSWORD}
=======
    username: postgres
    password: root123
>>>>>>> origin/coder

  jpa:
    hibernate:
      ddl-auto: update
<<<<<<< HEAD
>>>>>>> coder
=======
>>>>>>> origin/coder
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/